### ISSUE TITLE
Add chart for Switzerland including the nunber of persons in hospital

### ISSUE THREAD

**Issue by zukunft** [rsalzer/COVID_19_CH#1]
... and a line with the persons in ICU and maybe released.

**Comment by zukunft** [comment]
Thanks. Seen it.

**Comment by zukunft** [comment]
By the way: I have asked the missing Cantons for a data update.

**Comment by rsalzer** [comment]
> By the way: I have asked the missing Cantons for a data update.

Thank you! When we have all the data probably the whole visualisation will be made much nicer by the newspapers anyway...

**Comment by zukunft** [comment]
True. But maybe a "small" thing Can the x axis between synced between the number of cases and the hospital number? E.g. Freiburg looks a little bit strange.

**Comment by zukunft** [comment]
By the way, TA Media has started sharing: https://gitlab.com/ta-interaktiv

**Comment by rsalzer** [comment]
> True. But maybe a "small" thing Can the x axis between synced between the number of cases and the hospital number? E.g. Freiburg looks a little bit strange.

You are right ... I just commited that

**Comment by zukunft** [comment]
Thanks. Nice. Now we "just" need the data ...
