### ISSUE TITLE
Make date axis same scale

### ISSUE THREAD

**Issue by gaberoo** [rsalzer/COVID_19_CH#11]
In my view, I think it would be helpful to have the x axes (date) on the same scale for all cantons. What is your feeling on this?

**Comment by rsalzer** [comment]
Good point. Changed in https://github.com/rsalzer/COVID_19_CH/commit/d0b373970328e70158c9eea79f4693c02ffc9ba3

The minimum is now 2020-02-25, that was the first reported case in Ticino.
I also changed the maximum to be now (new Date()), so there is also a bit of space at the right side of the chart.

**Comment by gaberoo** [comment]
Great, thanks! I think this is much more informative... I hope you do too!
