### ISSUE TITLE
Left-align numbers showing increase since last data point

### ISSUE THREAD

**Issue by krlmlr** [rsalzer/COVID_19_CH#17]
Otherwise e.g. Zurich shows as "+18" today but the data suggests it's more like "+180".

Alternatively, extend the x scale or avoid clipping?

**Comment by rsalzer** [comment]
Good point, was struggling with that for a while ... I will look into it again.

**Comment by rsalzer** [comment]
I just pushed a new version with padding ... is it better now?

**Comment by krlmlr** [comment]
Much better, thanks!
