### ISSUE TITLE
FL to be excluded?

### ISSUE THREAD

**Issue by JBeyel** [rsalzer/COVID_19_CH#2]
As https://www.worldometers.info/coronavirus/#countries uses your numbers to update their case count it might be better to exclude FL (as a canton). There is no hugh difference of course, but FL is counted on its own on this page as it is a seperate country of course.

**Comment by rsalzer** [comment]
My total numbers (CH) are without the FL cases.
Also the source of my data is this official respository: https://github.com/openZH/covid_19
