### ISSUE TITLE
Relative number / percentages

### ISSUE THREAD

**Issue by tschiemer** [rsalzer/COVID_19_CH#20]
Hi, many thanks for setting this up!

What would be nice in most tables would be additional info giving a better impression of the situation instead of just the absolute numbers without context, thus also eliminating the need of manual comparison and other sources.

Such as:
- infected/international table: total population and percentage of infected
- infection/hostpitalization/icu/deceased/etc table: percentage of population/hospitalized/etc

**Comment by rsalzer** [comment]
Yes, cases / deaths etc. per 100'000 would be also interesting.
I will probably start with the international-numbers first.

**Comment by rsalzer** [comment]
What do you think?
<img width="664" alt="image" src="https://user-images.githubusercontent.com/17248257/78590015-6de2aa00-7841-11ea-834e-55e32fdbbbca.png">

**Comment by tschiemer** [comment]
As for resolving the number of infections/deaths relative to the overall population that is fine except for the missing overall population per country - which isn't necessary for that matter, but might be interesting numbers to have at hand. But as the goal is rather to show the spread of the virus in a simple way without too much info, that might be too much info ;)

But  the death count I would also put it into direct relation with the number of infections, ie for Switzerland that would be 89 deaths per million residents  which is ~3.5% of infections.  This would give an indication of the differences by a country's general conditions and its methods of handling of virus.

Other statistics I've seen lately would show vast differences in deaths ranging from 2% upto 33% or so - but I guess there's also been data missing, for that matter.

**Comment by rsalzer** [comment]
Hmm ... because the countries / cantons don't test on the same level for me actually the most reliable number is still per capita (and unfortunately ... deaths per capita)
