### ISSUE TITLE
Daily cases recalculation

### ISSUE THREAD

**Issue by No1e** [rsalzer/COVID_19_CH#21]
Hello Rsalzer,

First of all, nice work. 

I noticed that reporting from cantons are often done with delay, and introduces an error on all statistics. For example, VD and GE are often late, even two days.
![image](https://user-images.githubusercontent.com/25526781/79066355-8d515b00-7cb7-11ea-9d1f-6fdcd5a03fe6.png)

You might want to introduce recalculation that will try to correct the error. The recalculation should 
1. Execute every day at the end of the day
2. Go through all incomplete days
3. Find if there are updates for cantons. If yes recalculate statistics for that day

In this way we can get accurate information, and see if we are doing good job in flattening the curve. 

Cheers, have a good days and stay healthy,
Nole

**Comment by rsalzer** [comment]
Hey. Thanks!

So actually it already does all you are saying.
It is updating itself on every reload and using the updated data. So old days get more reliable once data is there and new gets updated. Just hover over older days and you will see.
