### ISSUE TITLE
Unvollständige Daten von Genf führen zu einer falschen Summer der Todesfälle

### ISSUE THREAD

**Issue by zukunft** [rsalzer/COVID_19_CH#25]
Die Daten von Genf sind derzeit 26.04.2020 22:58 nicht komplett. In der letzten Zeile fehlt zum Beispiel die Anzahl der Todesfälle. Dies führt dazu, dass eine falsche Summe der Todesfälle angezeigt wird. Entweder sollte für die Tabelle den Vortageswert verwendet werden oder die Originaldaten sollten immer aufgefüllt werden.

**Comment by rsalzer** [comment]
Merci für den Hinweis. Da hat sich ein Typo eingeschlichen beim letzten Fix.
