### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by dkoltg** [rsalzer/COVID_19_CH#26]
Hi, your link on the front page to the csv for charts of Switzerland as a whole does not work any more. Is there a new link? Thanks

**Comment by rsalzer** [comment]
Hi. Which link? Can you please specify?

**Comment by dkoltg** [comment]
https://github.com/openZH/covid_19/blob/master/COVID19_Cases_Cantons_CH_total.csv

**Comment by dkoltg** [comment]
I used your link to load the aggregated data in R, however the output is also somewhat strange for the dates before the May, 30 (numbers are a lot lower than they should be)...

**Comment by rsalzer** [comment]
Ah ... you mean in the readme here ... I thought you refer to my tracker.
There is the "old" version:
https://raw.githubusercontent.com/openZH/covid_19/master/COVID19_Fallzahlen_CH_total.csv
And the new one:
https://raw.githubusercontent.com/openZH/covid_19/master/COVID19_Fallzahlen_CH_total_v2.csv

**Comment by dkoltg** [comment]
For my R-process I use the following url https://open-covid-19.github.io/data/data.csv. Is there also a new version available? Till end of May the empty spaces contained the numbers for Switzerland in total, now the numbers are a lot lower. Have you modified anything in the code that generates this file?
