### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by AnLAdmin** [rsalzer/COVID_19_CH#30]
Hi,

Wäre schön, wenn die Anzahl Test auch irgendwie einfliessen könnten. Damit liesse sich die gefundenen Fälle besser gewichten.

**Comment by rsalzer** [comment]
Hallo,
Daran hab ich auch schon gedacht. Das Problem mit den Anzahl Tests ist, dass diese nicht von den Kantonen selbst (oder nur von wenigen ...) direkt gemeldet wird, sondern nur vom BAG. Und das BAG hat seine eigene Seite, die wie ich finde mittlerweile gut genug ist als dass man sie kopieren müsste ;)
https://www.covid19.admin.ch/de/overview/tests?detRel=abs

**Comment by AnLAdmin** [comment]
Danke für die Site, die hab ich übersehen.
