### ISSUE TITLE
not mobile friendly; unstyled

### ISSUE THREAD

**Issue by rsalzer** [rsalzer/COVID_19_CH#5]
beautify tables; make responsive

**Comment by rsalzer** [comment]
This could be a clue ... https://stackoverflow.com/questions/42340342/cant-make-chart-js-responsive

**Comment by rsalzer** [comment]
I addded width 100% and max-width 1000px to canvas. Still looks a bit small on mobile.
https://github.com/rsalzer/COVID_19_CH/commit/5ff722c7f7ca8a344ee7b75d8fb0776017054373

**Comment by zukunft** [comment]
Yes, a little bit small, but don't change too much. For me this pure visualization is the best. Thanks.

**Comment by rsalzer** [comment]
new design ... still will be tweaked ... close this for now
