### ISSUE TITLE
Total cases for Switzerland not correct

### ISSUE THREAD

**Issue by JBeyel** [rsalzer/COVID_19_CH#6]
Sorry to bother you again. I really appreciate your work and effort and I know that you get your data from official sites. I handcalculated the total of the cases after 7 new enteries today. The total number of cases for Switzerland was by then at 12076. My calculation showed that this included FL with 56 cases. The 26 cantons only added up to 12020 cases.

**Comment by rsalzer** [comment]
Oh wow ... that was a typo.
Thank you! I corrected it in the last commit. 
https://github.com/rsalzer/COVID_19_CH/commit/1c5afba8ac0730a1db9551d3f194a7d7d5396b55
Should be right now.

**Comment by rsalzer** [comment]
Can you check it one more time? If right now, I will close the issue.

**Comment by JBeyel** [comment]
Now it is correct.
